Feature/docker
training-of-new-employees/frontend pull request #38
Opened 2023-12-13 13:35 UTC by snurnisyan

2023-12-13 20:13 UTC, Elizaveta-Parada approved these changes

2023-12-14 07:08 UTC, Nexadis requested changes
Может лучше лить в develop ветку?

2023-12-14 07:08 UTC, Nexadis commented on .editorconfig
Не стоит заливать свои конфиги в репу

2023-12-14 07:08 UTC, Nexadis commented on Dockerfile
Лучше его не добавлять при merge, а взять dockerfile с nginz

2023-12-14 07:08 UTC, Nexadis commented on package.json
Уберите пожалуйста frontend в конце homepage, чтоб он не редиректил на /frontend при переходах, а ходил на /

2023-12-14 11:07 UTC, Nexadis requested changes

2023-12-14 11:07 UTC, Nexadis commented on Dockerfile
> +RUN REACT_APP_BASE_URL=http://localhost:8081 npm build
Переменная окружения прикидывается при сборке через ARG выше, это позволяет пересобрать образ с различными аргументами, не меняя сам dockerfile, поэтому надо убрать явное назначение переменной окружения.

Собирать образ лучше через npm run build, насколько мне известно:

npm build and npm run build are entirely different.
npm run build - This command runs the build field from the package.json scripts field.
npm build - It is an internal command. If you run it you'll get: npm WARN build npm build called with no arguments.

2023-12-14 11:25 UTC, Nexadis approved these changes

2023-12-14 11:42 UTC, merged